# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# from REST_INFO 
# where FAVORITES in (select max(favorites) from REST_INFO group by FOOD_TYPE)
# group by FOOD_TYPE
# order by FAVORITES desc

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (SELECT MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC

# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# from REST_INFO 
# order by FAVORITES desc
