
SELECT 
    COUNT(T1.ID) AS FISH_COUNT,
    MAX(T1.LENGTH) AS MAX_LENGTH,
    T1.FISH_TYPE
FROM FISH_INFO T1
RIGHT JOIN (
    SELECT 
        FISH_TYPE,
        AVG(LENGTH) AS AVG_LENGHT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(LENGTH) > 33
) T2
ON T1.FISH_TYPE = T2.FISH_TYPE
GROUP BY T1.FISH_TYPE
ORDER BY FISH_TYPE ASC